# Generated by Django 5.1.4 on 2025-01-04 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_currency_room_cost_limit_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
