# Generated by Django 5.1.4 on 2025-01-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='draw_started',
            field=models.BooleanField(default=False),
        ),
    ]
